image: ubuntu:17.10

stages:
  - test
  - deploy

before_script:
  - apt-get update && apt-get upgrade -qy
  - apt-get install -qy curl

test:
  stage: test
  script:
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install -qy python3.6 python3-pip python3-dev nodejs
    - pip3 install tox
    - tox --recreate -e py36 && tox -e dev
    - cd tripplanner/webapp/js
    - npm install && npm test

deploy:
  stage: deploy
  script:
    - apt-get install -qy ruby-full git
    - gem install dpl
    - dpl --provider=heroku --app=pirtplanner --api-key=$HEROKU_MASTER_API_KEY
  only:
    - master
