image: python:3.6

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -qy python3-dev python3-pip
    - python3 --version
    - python3.6 --version
    - pip3 install tox
    - tox

deploy:
  stage: deploy
  script:
    - echo "deploying"
